@baseUrl = http://localhost:8081

### Get Token
# @name getToken

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "punnawat",
  "password": "123456"
}

### Create User with Token
POST {{baseUrl}}/user/create
Content-Type: application/json
Authorization: Bearer {{getToken.response.body.$.data.access_token}}

{
  "username": "punnawatnew3Admin",
  "password": "123456",
  "role": "ADMIN"
}