name: CD - Build & Deploy

on:
  push:
    branches: ["dev"]

env:
  REGISTRY: ghcr.io

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    outputs:
      image: ${{ steps.image.outputs.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Set image name
        id: image
        run: |
          IMAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ steps.image.outputs.name }}:latest .

      - name: Push
        run: |
          docker push ${{ env.REGISTRY }}/${{ steps.image.outputs.name }}:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup SSH key
        run: |
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY_B64 }}" | base64 -d > key
          chmod 600 key

      - name: Deploy
        run: |
          ssh -i key -o StrictHostKeyChecking=no ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} << EOF

            set -e
            cd /app

            IMAGE=$(echo "${{ needs.build.outputs.image }}" | tr '[:upper:]' '[:lower:]')

            echo "📦 Pulling image..."
            docker pull ghcr.io/$IMAGE:latest

            echo "🧱 Running migrations..."
            docker compose -f docker-compose.prod.yml run --rm migrate

            echo "🔄 Restarting app..."
            docker compose -f docker-compose.prod.yml up -d

            echo "🧹 Cleaning old images..."
            docker image prune -f

            echo "✅ Done"

          EOF
